apiVersion: v1
kind: Namespace
metadata:
   name: reactfrontend
   labels:
     app.kubernetes.io/name: dotnetapp
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dotnetapp
  namespace: reactfrontend
  labels:
    app.kubernetes.io/name: dotnetapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: dotnetapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dotnetapp
    spec:
     containers:
       - name: frontend
         image: 519852036875.dkr.ecr.us-west-2.amazonaws.com/myrepo:${BITBUCKET_BUILD_NUMBER}
         imagePullPolicy: Always
         ports:
           - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnetapp
  namespace: reactfrontend
  labels:
    app.kubernetes.io/name: dotnetapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dotnetapp